import type { Metadata } from "next";
import "./globals.css";
import { DM_Serif_Display, Be_Vietnam_Pro } from 'next/font/google'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSerif = DM_Serif_Display({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-dm-serif',
})

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-be-vietnam-pro',
  weight: ['400', '500', '600'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} ${dmSerif.variable} ${beVietnamPro.variable} antialiased`}>
      <body className={`${beVietnamPro.className} min-h-screen bg-[#f6f6ea80]`}>
        {children}
      </body>
    </html>
  );
}
